pref( "extensions.psicotsi.prefs.HTURL", "^http:\/\/(stage\.|www\d*\.|www\.new\.|wwwxx\.){0,1}hattrick\.(org|ws|interia\.pl)" );
pref( "extensions.psicotsi.prefs.htLanguage", "en");
pref( "extensions.psicotsi.prefs.htCurrency", "EUR");
pref( "extensions.psicotsi.prefs.htCurrencyName", "€");
pref( "extensions.psicotsi.prefs.htCurrencyRate", "1.0");
pref( "extensions.psicotsi.prefs.showWage", false);
pref( "extensions.psicotsi.prefs.PrefsSavedOnce", true);
pref( "extensions.psicotsi.prefs.showAlertBox", false);
pref( "extensions.psicotsi.prefs.showSearchPage", false);
pref( "extensions.psicotsi.prefs.hideUnderSkills", false);
pref( "extensions.psicotsi.prefs.showLeftMenu", false);
pref( "extensions.psicotsi.prefs.statusbarshow", false);
pref( "extensions.psicotsi.prefs.statusbarshowreload", false);
pref( "extensions.psicotsi.prefs.disableOnStage", false);
pref( "extensions.psicotsi.prefs.disableTemporary", false);
pref( "extensions.psicotsi.prefs.reloadPsicoDev", false);